# Workflow to build a custom image using Packer and run integration tests on the application.
name: Build Custom Image

on:
  pull_request:
    types: [closed]
    branches: [main]

env: 
  PKR_VERSION: "1.8.5" 
  JAVA_VERSION: "19"   
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  # The job integration-tests runs on the latest Ubuntu environment
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    # Define the postgres service required for the job
    services:
      postgres:
        image: postgres:16
        # Environment variables for the Postgres database, fetched from GitHub Secrets
        env:
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        # Configure health required checks for the Postgres service
        options: >-
          --health-cmd="pg_isready -U $DB_USERNAME -d $DB_NAME"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Step 1: Checkout the repository to get the latest code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Java 19
      - name: Set Up Java v19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'

      # Step 3: Set environment variables required for database connection
      - name: Set Environment Variables
        run: |
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV

      # Step 4: Verify that the database is accessible
      - name: Verify Database Connection
        run: |
          sudo apt-get install -y postgresql-client
          PGPASSWORD=${{ env.DB_PASSWORD }} psql -h ${{ env.DB_HOST }} -U ${{ env.DB_USERNAME }} -d ${{ env.DB_NAME }} -c "SELECT 1;"

      # Step 5: Create the test schema if it does not exist
      - name: Create Schema if Not Exists
        run: |
          sudo apt-get install -y postgresql-client
          PGPASSWORD=${{ env.DB_PASSWORD }} psql -h ${{ env.DB_HOST }} -U ${{ env.DB_USERNAME }} -d ${{ env.DB_NAME }} -c "
          DO \$\$
          BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_namespace WHERE nspname = 'test') THEN
              CREATE SCHEMA test;
            END IF;
          END;
          \$\$
          "

      # Step 6: Build and run tests
      - name: Build and Zip Application
        run: |
          mvn clean package
          cd target
          zip -r webapp.zip webapp-0.0.1-SNAPSHOT.jar
      
      # Step 7: Upload the zipped application as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp-zip
          path: target/webapp.zip    
       
  build-image:
    # This job builds the custom image using Packer
    name: Build Custom Image
    needs: integration-tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      # Step 1: Checkout the repository to get the latest code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Download the zipped application artifact
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp-zip
          path: target        
      
      # Step 3: Set up AWS credentials for DEV account
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 4: Set up Packer    
      - name: Setup Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: ${{ env.PKR_VERSION }}

      # Step 5: Initialize the Packer template    
      - name: Initialize Packer Template
        run: |
          cd packer
          packer init .      
      
      # Step 6: Build the custom image using Packer    
      - name: Build Image and Extract AMI ID
        id: build-ami
        run: |
          cd packer
          AMI_ID=$(packer build -machine-readable -color=false -on-error=abort \
          -var "aws_demo_account_id=${{ secrets.AWS_DEMO_ACCOUNT_ID }}" \
          -var "db_name=${{ secrets.DB_NAME }}" \
          -var "db_username=${{ secrets.DB_USERNAME }}" \
          -var "db_password=${{ secrets.DB_PASSWORD }}" \
          -var "github_workspace=${{ github.workspace }}" \
          -var "aws_region=${{ env.AWS_REGION }}" \
          webapp.pkr.hcl | tee /tmp/packer-output.log | grep 'artifact,0,id' | cut -d, -f6 | cut -d: -f2)
          
          echo "Extracted AMI ID: $AMI_ID"
          
          if [ -z "$AMI_ID" ]; then
          echo "AMI ID extraction failed."
          cat /tmp/packer-output.log
          exit 1
          fi
          
          echo "ami_id=$AMI_ID" >> $GITHUB_OUTPUT

      # Step 7: Reconfigure AWS credentials for DEMO account
      - name: Reconfigure AWS for DEMO Account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEMO_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEMO_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 8: Create a new launch template version with the new AMI ID    
      - name: Create New Launch Template Version
        id: lt-version
        run: |
          VERSION=$(aws ec2 create-launch-template-version \
            --launch-template-id "${{ secrets.LAUNCH_TEMPLATE_ID }}" \
            --source-version 1 \
            --launch-template-data "{\"ImageId\":\"${{ steps.build-ami.outputs.ami_id }}\"}" \
            --query 'LaunchTemplateVersion.VersionNumber' \
            --output text)
          
          echo "Launch Template Version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # Step 9: Update the Auto Scaling Group with the new launch template version    
      - name: Update Auto Scaling Group
        run: |
          aws autoscaling update-auto-scaling-group \
            --auto-scaling-group-name "${{ secrets.ASG_NAME }}" \
            --launch-template "LaunchTemplateId=${{ secrets.LAUNCH_TEMPLATE_ID }},Version=${{ steps.lt-version.outputs.version }}"

      # Step 10: Start Instance Refresh for the Auto Scaling Group      
      - name: Start Instance Refresh
        id: instance-refresh
        run: |
          REFRESH_ID=$(aws autoscaling start-instance-refresh \
            --auto-scaling-group-name "${{ secrets.ASG_NAME }}" \
            --strategy Rolling \
            --query 'InstanceRefreshId' \
            --output text)
          
          echo "refresh_id=$REFRESH_ID" >> $GITHUB_OUTPUT

      # Step 11: Wait for Instance Refresh to Complete    
      - name: Wait for Instance Refresh to Complete
        run: |
          REFRESH_ID=${{ steps.instance-refresh.outputs.refresh_id }}
          ASG_NAME="${{ secrets.ASG_NAME }}"
          
          echo "Waiting for instance refresh $REFRESH_ID on ASG $ASG_NAME..."
          
          STATUS="Pending"
          ATTEMPTS=0
          MAX_ATTEMPTS=50 
          
          while { [ "$STATUS" == "Pending" ] || [ "$STATUS" == "InProgress" ]; } && [ $ATTEMPTS -lt $MAX_ATTEMPTS ]; do
            STATUS=$(aws autoscaling describe-instance-refreshes \
              --auto-scaling-group-name "$ASG_NAME" \
              --instance-refresh-ids "$REFRESH_ID" \
              --query 'InstanceRefreshes[0].Status' \
              --output text)
          
            echo "Attempt $((ATTEMPTS + 1)) - Current status: $STATUS"
          
            if [ "$STATUS" == "Successful" ]; then
              echo "Instance refresh completed successfully."
              exit 0
            fi
          
            sleep 30
            ATTEMPTS=$((ATTEMPTS + 1))
          done
          
          # Final status check
          if [ "$STATUS" == "Successful" ]; then
            echo "Instance refresh completed successfully."
            exit 0
          elif [ $ATTEMPTS -ge $MAX_ATTEMPTS ]; then
            echo "Timeout reached after $MAX_ATTEMPTS attempts (~10 minutes). Last status: $STATUS"
          else
            echo "Instance refresh failed with status: $STATUS"
            exit 1
          fi