# Workflow to validate Packer templates
name: Packer Template Validation

on:
  pull_request:
    branches: 
      - main
    types: [opened, synchronize, reopened]  

env: 
  PKR_VERSION: "1.8.5"    
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  # Job to validate Packer templates
  validate:
    name: Validate Packer Template
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository to get the latest code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Packer  
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PKR_VERSION }} 

      # Step 3: Initialize Packer    
      - name: Initialize Packer
        run: |
          cd packer
          packer init .   
      
      # Step 4: Build and Zip Application    
      - name: Build and Zip Application
        run: |
            mvn clean package -DskipTests
            cd target
            zip -r webapp.zip webapp-0.0.1-SNAPSHOT.jar    

      # Step 5: Packer Format Check      
      - name: Packer Format Check
        run: |
          cd packer
          packer fmt -check .

      # Step 6: Validate Packer Template    
      - name: Packer Validate
        run: |
          cd packer
          packer validate \
            -var "aws_demo_account_id=${{ secrets.AWS_DEMO_ACCOUNT_ID }}" \
            -var "db_name=${{ secrets.DB_NAME }}" \
            -var "db_username=${{ secrets.DB_USERNAME }}" \
            -var "db_password=${{ secrets.DB_PASSWORD }}" \
            -var "github_workspace=${{ github.workspace }}" \
            -var "aws_region=${{ env.AWS_REGION }}" .